### ISSUE TITLE
[Feature request] Auto load hardware codec

### ISSUE THREAD

**Issue by chrisxvin** [bswebdk/FFQueue#15]
Now hardware codecs are only visible when activated "Enable full codec listings", so I suggest if you can detect GPUs and load related codecs to default list.
I think this will be useful.

**Comment by bswebdk** [comment]
FFQueue has a list of "[well known codecs](https://github.com/bswebdk/FFQueue/blob/master/src/utils/FFQCodecInfo.cpp#L50)" for which extended info is baked into the source and these codecs are shown in the limited codec list. I may at some point in the future add more codecs to that list but it has not been a priority since all codecs are available anyway.
