### ISSUE TITLE
[Feature Request] - "Copy if already «selected format»" for audio

### ISSUE THREAD

**Issue by j7j2** [bswebdk/FFQueue#23]
When making repacks and wanting to make the output compliant to the next thing, if one of the audio tracks is already aac, I don't want it to be re-encoded again resulting in even worst lossy to lossy re-compression. Having a simple checkbox above the drop menu in the audio page would save a few steps of work.

**Comment by bswebdk** [comment]
I am looking at this... :-)

**Comment by bswebdk** [comment]
Available in V1.7.63

**Comment by j7j2** [comment]
Hi there. Sorry if i was ever rude, didn't meant to be.

Didn't had time to reply sooner but on a new system, I made some more tests and I'm able to replicate the issue. Looks that when I'm using my old version 5.1 animmouse non free  ffmpeg thing, everything is fine tho when I install either the latest animmouse version or the original on ffmpeg website, the script encode two video track instead of one.

Since i didn't noticed in the first place that the video file contained two video tracks switcheable via vlc video track menu... there was a confusion as why no tools would tell me the same info of what's the true resolution.

that's the log with the new ffmpeg version with a simple resize 680*456 + pad to 704*480

Have ffmpeg changed how maping should be stated regarding complex filter chains?

Here is the generated command: ffmpeg -i "\\Leo-pc\z\qBittorrent\incoming\cat-movies\The Prisoner 1967 Season 1 Complete UPDATED 720p BluRay x264 [i_c]\The Prisoner S01E01 Arrival.mkv" -map 0:0 -map 0:1 -filter_complex "[0:0]scale=680:456:flags=lanczos[F1];[F1]pad=704:480:(ow-iw)/2:(oh-ih)/2:#000000" -c:v libx264 -crf 12 -preset:v veryslow -bf 3 -refs 9 -pix_fmt yuv420p -c:a aac -b:a 512k -ac 2 -movflags faststart -aspect 4:3 -f mp4 -y "E:\Le Prisoner SD\1.7.64.310.mp4"

and either when run manually or with ffqueue, i get the double video encode thing as you can see below

Starting FFMpeg 2024/03/01 19:36:44 with command: -hide_banner -i "\\Leo-pc\z\qBittorrent\incoming\cat-movies\The Prisoner 1967 Season 1 Complete UPDATED 720p BluRay x264 [i_c]\The Prisoner S01E01 Arrival.mkv" -map 0:0 -map 0:1 -filter_complex "[0:0]scale=680:456:flags=lanczos[F1];[F1]pad=704:480:(ow-iw)/2:(oh-ih)/2:#000000" -c:v libx264 -crf 12 -preset:v veryslow -bf 3 -refs 9 -pix_fmt yuv420p -c:a aac -b:a 512k -ac 2 -movflags faststart -aspect 4:3 -f mp4 -y "E:\Le Prisoner SD\1.7.64.310.mp4"

Input #0, matroska,webm, from '\\Leo-pc\z\qBittorrent\incoming\cat-movies\The Prisoner 1967 Season 1 Complete UPDATED 720p BluRay x264 [i_c]\The Prisoner S01E01 Arrival.mkv':
Metadata:
creation_time   : 2021-06-19T13:05:14.000000Z
ENCODER         : Lavf58.29.100
Duration: 00:50:58.98, start: 0.000000, bitrate: 2571 kb/s
Stream #0:0: Video: h264 (Main), yuv420p(tv, bt709, progressive), 1280x720 [SAR 719:960 DAR 719:540], 24 fps, 24 tbr, 1k tbn (default)
Metadata:
DURATION        : 00:50:58.980000000
Stream #0:1(eng): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
Metadata:
title           : Stereo
DURATION        : 00:50:58.005000000
Stream #0:2(eng): Subtitle: ass
Metadata:
DURATION        : 00:49:34.478000000
Stream mapping:
Stream #0:0 (h264) -> scale:default (graph 0)
pad:default (graph 0) -> Stream #0:0 (libx264)
Stream #0:0 -> #0:1 (h264 (native) -> h264 (libx264))
Stream #0:1 -> #0:2 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 00000000001c6400] using SAR=3/4
[libx264 @ 00000000001c6400] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
[libx264 @ 00000000001c6400] profile High, level 4.0, 4:2:0, 8-bit
[libx264 @ 00000000001c6400] 264 - core 164 r3172 c1c9931 - H.264/MPEG-4 AVC codec - Copyleft 2003-2023 - http://www.videolan.org/x264.html - options: cabac=1 ref=9 deblock=1:0:0 analyse=0x3:0x133 me=umh subme=10 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=24 chroma_me=1 trellis=2 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=2 b_bias=0 direct=3 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=24 scenecut=40 intra_refresh=0 rc_lookahead=60 rc=crf mbtree=1 crf=12.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[libx264 @ 00000000001c3d80] using SAR=10/11
[libx264 @ 00000000001c3d80] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
[libx264 @ 00000000001c3d80] profile High, level 3.1, 4:2:0, 8-bit
[libx264 @ 00000000001c3d80] 264 - core 164 r3172 c1c9931 - H.264/MPEG-4 AVC codec - Copyleft 2003-2023 - http://www.videolan.org/x264.html - options: cabac=1 ref=9 deblock=1:0:0 analyse=0x3:0x133 me=umh subme=10 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=24 chroma_me=1 trellis=2 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=2 b_bias=0 direct=3 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=24 scenecut=40 intra_refresh=0 rc_lookahead=60 rc=crf mbtree=1 crf=12.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'E:\Le Prisoner SD\1.7.64.310.mp4':
**_Metadata:
encoder         : Lavf60.20.100
Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 704x480 [SAR 10:11 DAR 4:3], q=2-31, 24 fps, 12288 tbn
Metadata:
encoder         : Lavc60.36.100 libx264
Side data:
cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
Stream #0:1: Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1280x720 [SAR 3:4 DAR 4:3], q=2-31, 24 fps, 12288 tbn (default)
Metadata:
DURATION        : 00:50:58.980000000
encoder         : Lavc60.36.100 libx264
Side data:
cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
Stream #0:2(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 512 kb/s (default)
Metadata:_**
title           : Stereo
DURATION        : 00:50:58.005000000
encoder         : Lavc60.36.100 aac
frame=   23 fps= 11 q=17.0 q=17.0 size=       0kB time=00:00:00.83 bitrate=   0.5kbits/s speed=0.403x
frame=   26 fps= 10 q=17.0 q=17.0 size=     256kB time=00:00:00.91 bitrate=2288.2kbits/s speed=0.354x
frame=   29 fps=9.4 q=17.0 q=17.0 size=     256kB time=00:00:01.08 bitrate=1936.2kbits/s speed=0.35x
frame=   34 fps=9.3 q=17.0 q=17.0 size=     512kB time=00:00:01.25 bitrate=3355.8kbits/s speed=0.342x
frame=   37 fps=8.8 q=17.0 q=17.0 size=     512kB time=00:00:01.37 bitrate=3050.7kbits/s speed=0.327x
[q] command received. Exiting.
[mp4 @ 00000000001c6a40] Starting second pass: moving the moov atom to the beginning of the file
[out#0/mp4 @ 0000000002bd7e80] video:4294kB audio:139kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.168280%
frame=  124 fps=7.1 q=-1.0 Lq=-1.0 size=    4440kB time=00:00:04.94 bitrate=7349.1kbits/s dup=3 drop=0 speed=0.282x
[libx264 @ 00000000001c3d80] frame I:2     Avg QP: 4.80  size: 39806
[libx264 @ 00000000001c3d80] frame P:33    Avg QP:10.11  size: 25383
[libx264 @ 00000000001c3d80] frame B:89    Avg QP:12.16  size:  8399
[libx264 @ 00000000001c3d80] consecutive B-frames:  3.2%  3.2%  0.0% 93.5%
[libx264 @ 00000000001c3d80] mb I  I16..4: 53.3% 29.5% 17.2%
[libx264 @ 00000000001c3d80] mb P  I16..4:  1.6% 27.8%  2.5%  P16..4: 16.1% 15.9% 11.8%  1.4%  0.6%    skip:22.2%
[libx264 @ 00000000001c3d80] mb B  I16..4:  0.1%  4.1%  0.0%  B16..8: 20.5% 11.9%  7.0%  direct:19.8%  skip:36.7%  L0:36.3% L1:35.2% BI:28.6%
[libx264 @ 00000000001c3d80] 8x8 transform intra:82.6% inter:34.0%
[libx264 @ 00000000001c3d80] direct mvs  spatial:84.3% temporal:15.7%
[libx264 @ 00000000001c3d80] coded y,uvDC,uvAC intra: 89.0% 91.3% 89.1% inter: 34.7% 48.3% 22.6%
[libx264 @ 00000000001c3d80] i16 v,h,dc,p: 68% 16%  3% 14%
[libx264 @ 00000000001c3d80] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 10% 15% 20%  7%  9%  8% 10%  8% 14%
[libx264 @ 00000000001c3d80] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 10% 15% 10%  7% 12%  8% 12%  9% 17%
[libx264 @ 00000000001c3d80] i8c dc,h,v,p: 62% 20% 10%  8%
[libx264 @ 00000000001c3d80] Weighted P-Frames: Y:18.2% UV:18.2%
[libx264 @ 00000000001c3d80] ref P L0: 51.3% 11.8% 19.7%  7.1%  3.8%  2.3%  1.9%  1.1%  0.9%
[libx264 @ 00000000001c3d80] ref B L0: 87.7%  6.8%  2.5%  1.1%  0.8%  0.6%  0.3%  0.2%
[libx264 @ 00000000001c3d80] ref B L1: 97.4%  2.6%
[libx264 @ 00000000001c3d80] kb/s:2577.73
[libx264 @ 00000000001c6400] frame I:2     Avg QP: 4.31  size: 72148
[libx264 @ 00000000001c6400] frame P:32    Avg QP: 9.99  size: 42892
[libx264 @ 00000000001c6400] frame B:90    Avg QP:13.24  size: 13485
[libx264 @ 00000000001c6400] consecutive B-frames:  3.2%  0.0%  0.0% 96.8%
[libx264 @ 00000000001c6400] mb I  I16..4: 54.3% 17.6% 28.1%
[libx264 @ 00000000001c6400] mb P  I16..4:  3.0% 14.3%  3.0%  P16..4: 30.4% 16.1% 10.4%  0.6%  0.3%    skip:22.0%
[libx264 @ 00000000001c6400] mb B  I16..4:  0.2%  1.8%  0.1%  B16..8: 34.5%  8.4%  2.6%  direct:12.6%  skip:39.7%  L0:44.3% L1:40.5% BI:15.2%
[libx264 @ 00000000001c6400] 8x8 transform intra:63.3% inter:29.3%
[libx264 @ 00000000001c6400] direct mvs  spatial:84.4% temporal:15.6%
[libx264 @ 00000000001c6400] coded y,uvDC,uvAC intra: 79.0% 82.7% 64.8% inter: 22.3% 47.0% 6.8%
[libx264 @ 00000000001c6400] i16 v,h,dc,p: 55% 14% 15% 16%
[libx264 @ 00000000001c6400] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 12% 19% 25%  6%  6%  6%  8%  6% 12%
[libx264 @ 00000000001c6400] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 13% 19% 13%  7% 10%  8% 11%  7% 13%
[libx264 @ 00000000001c6400] i8c dc,h,v,p: 61% 23% 12%  4%
[libx264 @ 00000000001c6400] Weighted P-Frames: Y:31.2% UV:31.2%
[libx264 @ 00000000001c6400] ref P L0: 52.5%  9.4% 22.0% 11.5%  2.4%  1.0%  0.6%  0.4%  0.3%  0.0%
[libx264 @ 00000000001c6400] ref B L0: 83.4% 10.6%  4.1%  0.8%  0.5%  0.3%  0.2%  0.1%
[libx264 @ 00000000001c6400] ref B L1: 96.2%  3.8%
[libx264 @ 00000000001c6400] kb/s:4227.93
[aac @ 000000000272fac0] Qavg: 65536.000

FFMpeg exited 2024/03/01 19:37:02, running time 00:00:17.722
Successfully completed with 9 lines of statistics!
The job was aborted!


Total processing time was 00:00:17.732

**Comment by bswebdk** [comment]
I do not recall you being rude. If you mean the redaction I made, that was about you posting your "real" name on a publicly accessible site along with information about your "downloading behaviour", and this may become unfortunate for you. You just posted info about you using qBittorrent to download "The Prisoner 1967 Season 1 Complete UPDATED 720p BluRay" to "Leo-pc" which is not very unfortunate..

I have tested your command with FFmpeg V4.4.2 on Ubuntu 22.04, and I simply cannot reproduce the problem, the output file contains no copy of the original video stream, only one video stream and one audio stream.

Your problem is most likely related to the source file or the version of FFmpeg used, and not FFQueue.

ffmpeg -hide_banner -i "/path/recording.tts" -map 0:0 -map 0:1 -filter_complex "[0:0]scale=680:456:flags=lanczos[F1];[F1]pad=704:480:(ow-iw)/2:(oh-ih)/2:#000000" -c:v libx264 -crf 12 -preset:v veryslow -bf 3 -refs 9 -pix_fmt yuv420p -c:a aac -b:a 512k -ac 2 -movflags faststart -aspect 4:3 -f mp4 -y "output.mp4"
[h264 @ 0x55b406028280] Increasing reorder buffer to 2
[mpegts @ 0x55b406021ac0] PES packet size mismatch
[mpegts @ 0x55b406021ac0] Packet corrupt (stream = 1, dts = 6424205888).
[mpegts @ 0x55b406021ac0] PES packet size mismatch
[mpegts @ 0x55b406021ac0] Packet corrupt (stream = 2, dts = 6424209738).
Input #0, mpegts, from '/path/recording.tts':
  Duration: 01:50:59.24, start: 64721.708200, bitrate: 15297 kb/s
  Program 1290 
  Stream #0:0[0xb54]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
  Stream #0:1[0xb55](eng): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 192 kb/s
  Stream #0:2[0xb5d](eng,eng,eng): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006), 492x250
Stream mapping:
  Stream #0:0 (h264) -> scale (graph 0)
  pad (graph 0) -> Stream #0:0 (libx264)
  Stream #0:1 -> #0:1 (mp2 (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 0x55b4064a0fc0] using SAR=10/11
[libx264 @ 0x55b4064a0fc0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x55b4064a0fc0] profile High, level 3.1, 4:2:0, 8-bit
[libx264 @ 0x55b4064a0fc0] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=9 deblock=1:0:0 analyse=0x3:0x133 me=umh subme=10 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=24 chroma_me=1 trellis=2 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=2 b_bias=0 direct=3 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=60 rc=crf mbtree=1 crf=12.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'output.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709, top coded first (swapped)), 704x480 [SAR 10:11 DAR 4:3], q=2-31, 25 fps, 12800 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
  Stream #0:1(dan): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 512 kb/s
    Metadata:
      encoder         : Lavc58.134.100 aac
[mp4 @ 0x55b4063de4c0] Starting second pass: moving the moov atom to the beginning of the file0 speed=1.39x    
frame= 1140 fps= 34 q=-1.0 Lsize=   18793kB time=00:00:45.48 bitrate=3385.1kbits/s dup=10 drop=0 speed=1.35x    
video:16362kB audio:2396kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.185191%
[libx264 @ 0x55b4064a0fc0] frame I:12    Avg QP:10.16  size: 68237
[libx264 @ 0x55b4064a0fc0] frame P:317   Avg QP:12.34  size: 27098
[libx264 @ 0x55b4064a0fc0] frame B:811   Avg QP:13.84  size:  9058
[libx264 @ 0x55b4064a0fc0] consecutive B-frames:  2.5%  3.5% 13.7% 80.4%
[libx264 @ 0x55b4064a0fc0] mb I  I16..4: 14.5% 52.8% 32.7%
[libx264 @ 0x55b4064a0fc0] mb P  I16..4:  2.6% 13.5%  3.4%  P16..4: 27.5% 24.5% 18.8%  1.7%  1.0%    skip: 6.9%
[libx264 @ 0x55b4064a0fc0] mb B  I16..4:  0.4%  2.0%  0.4%  B16..8: 27.4% 15.4%  6.0%  direct:13.4%  skip:35.0%  L0:46.7% L1:37.3% BI:16.0%
[libx264 @ 0x55b4064a0fc0] 8x8 transform intra:67.7% inter:37.2%
[libx264 @ 0x55b4064a0fc0] direct mvs  spatial:99.1% temporal:0.9%
[libx264 @ 0x55b4064a0fc0] coded y,uvDC,uvAC intra: 82.9% 90.3% 84.8% inter: 37.5% 31.7% 16.7%
[libx264 @ 0x55b4064a0fc0] i16 v,h,dc,p: 42% 23%  5% 30%
[libx264 @ 0x55b4064a0fc0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 18% 11% 14%  7%  9% 11%  8% 11% 10%
[libx264 @ 0x55b4064a0fc0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 18% 10% 12%  8% 11% 12%  8% 11% 10%
[libx264 @ 0x55b4064a0fc0] i8c dc,h,v,p: 43% 24% 20% 13%
[libx264 @ 0x55b4064a0fc0] Weighted P-Frames: Y:5.7% UV:5.0%
[libx264 @ 0x55b4064a0fc0] ref P L0: 46.1%  5.4% 17.1%  7.6%  6.9%  5.4%  5.3%  3.0%  3.1%  0.0%  0.0%
[libx264 @ 0x55b4064a0fc0] ref B L0: 70.6% 12.9%  6.2%  3.3%  2.6%  2.3%  1.5%  0.6%
[libx264 @ 0x55b4064a0fc0] ref B L1: 95.3%  4.7%
[libx264 @ 0x55b4064a0fc0] kb/s:2939.38
[aac @ 0x55b4062c2940] Qavg: 65385.453

**Comment by j7j2** [comment]
Yeah, I recall doing all of that and I see your point.

Sorry if it missinterpreted your initial comment. Frenchie here :-)

For the leak of my personal information... it's just that... I don't 
mind much about those things. I feel like I would be happy to wear a 
t-shirt saying "I download copyrighted movies for free ... and you paid 
5 times in your life to see the same Toy Story because you neither have 
a vhs or a dvd player anymore boomer"

For the issue I have with ffmpeg, I'll try to test the behavior of 
latest ffqueue with latest ffmpeg on windows 10 soon. I'm back to 
version 5.1 animmouse since that one works for now.

Might also go hang on libera.chat to see what some people thinks about 
the fact that I still sometimes use VirtualDub and Audition 1.5 
(Syntrillium cool edit pro...) XD

btw, Virtualdub is still used by a niche of people for cleaning up vhs 
rip, there are a few plugins that have been written especially for that 
and the fact that you have a live preview while tweaking their 
parameters really help.

Thanks for your work, really love your tool

Tommy :-)

On 2024-01-04 14:47, bswebdk wrote:

> I do not recall you being rude. If you mean the redaction I made, that 
> was about you posting your "real" name on a publicly accessible site 
> along with information about your "downloading behaviour", and this may 
> become unfortunate for you. You just posted info about you using 
> qBittorrent to download "The Prisoner 1967 Season 1 Complete UPDATED 
> 720p BluRay" to "Leo-pc" which is not very unfortunate..
> 
> I have tested your command with FFmpeg V4.4.2 on Ubuntu 22.04, and I 
> simply cannot reproduce the problem, the output file contains no copy 
> of the original video stream, only one video stream and one audio 
> stream..
> 
> ffmpeg -hide_banner -i "/path/recording.tts" -map 0:0 -map 0:1 
> -filter_complex 
> "[0:0]scale=680:456:flags=lanczos[F1];[F1]pad=704:480:(ow-iw)/2:(oh-ih)/2:#000000" 
> -c:v libx264 -crf 12 -preset:v veryslow -bf 3 -refs 9 -pix_fmt yuv420p 
> -c:a aac -b:a 512k -ac 2 -movflags faststart -aspect 4:3 -f mp4 -y 
> "output.mp4"
> [h264 @ 0x55b406028280] Increasing reorder buffer to 2
> [mpegts @ 0x55b406021ac0] PES packet size mismatch
> [mpegts @ 0x55b406021ac0] Packet corrupt (stream = 1, dts = 
> 6424205888).
> [mpegts @ 0x55b406021ac0] PES packet size mismatch
> [mpegts @ 0x55b406021ac0] Packet corrupt (stream = 2, dts = 
> 6424209738).
> Input #0, mpegts, from '/path/recording.tts':
> Duration: 01:50:59.24, start: 64721.708200, bitrate: 15297 kb/s
> Program 1290
> Stream #0:0[0xb54]: Video: h264 (High) ([27][0][0][0] / 0x001B), 
> yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 
> tbr, 90k tbn, 50 tbc
> Stream #0:10xb55 [1]: Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, 
> stereo, fltp, 192 kb/s
> Stream #0:20xb5d: Subtitle: dvb_teletext ([6][0][0][0] / 0x0006), 
> 492x250
> Stream mapping:
> Stream #0:0 (h264) -> scale (graph 0)
> pad (graph 0) -> Stream #0:0 (libx264)
> Stream #0:1 -> #0:1 (mp2 (native) -> aac (native))
> Press [q] to stop, [?] for help
> [libx264 @ 0x55b4064a0fc0] using SAR=10/11
> [libx264 @ 0x55b4064a0fc0] using cpu capabilities: MMX2 SSE2Fast SSSE3 
> SSE4.2 AVX FMA3 BMI2 AVX2
> [libx264 @ 0x55b4064a0fc0] profile High, level 3.1, 4:2:0, 8-bit
> [libx264 @ 0x55b4064a0fc0] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 
> AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - 
> options: cabac=1 ref=9 deblock=1:0:0 analyse=0x3:0x133 me=umh subme=10 
> psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=24 chroma_me=1 trellis=2 
> 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 
> threads=12 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 
> interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 
> b_adapt=2 b_bias=0 direct=3 weightb=1 open_gop=0 weightp=2 keyint=250 
> keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=60 rc=crf 
> mbtree=1 crf=12.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 
> aq=1:1.00
> Output #0, mp4, to 'output.mp4':
> Metadata:
> encoder : Lavf58.76.100
> Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709, top 
> coded first (swapped)), 704x480 [SAR 10:11 DAR 4:3], q=2-31, 25 fps, 
> 12800 tbn
> Metadata:
> encoder : Lavc58.134.100 libx264
> Side data:
> cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
> Stream #0:1(dan): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 
> stereo, fltp, 512 kb/s
> Metadata:
> encoder : Lavc58.134.100 aac
> [mp4 @ 0x55b4063de4c0] Starting second pass: moving the moov atom to 
> the beginning of the file0 speed=1.39x
> frame= 1140 fps= 34 q=-1.0 Lsize= 18793kB time=00:00:45.48 
> bitrate=3385.1kbits/s dup=10 drop=0 speed=1.35x
> video:16362kB audio:2396kB subtitle:0kB other streams:0kB global 
> headers:0kB muxing overhead: 0.185191%
> [libx264 @ 0x55b4064a0fc0] frame I:12 Avg QP:10.16 size: 68237
> [libx264 @ 0x55b4064a0fc0] frame P:317 Avg QP:12.34 size: 27098
> [libx264 @ 0x55b4064a0fc0] frame B:811 Avg QP:13.84 size: 9058
> [libx264 @ 0x55b4064a0fc0] consecutive B-frames: 2.5% 3.5% 13.7% 80.4%
> [libx264 @ 0x55b4064a0fc0] mb I I16..4: 14.5% 52.8% 32.7%
> [libx264 @ 0x55b4064a0fc0] mb P I16..4: 2.6% 13.5% 3.4% P16..4: 27.5% 
> 24.5% 18.8% 1.7% 1.0% skip: 6.9%
> [libx264 @ 0x55b4064a0fc0] mb B I16..4: 0.4% 2.0% 0.4% B16..8: 27.4% 
> 15.4% 6.0% direct:13.4% skip:35.0% L0:46.7% L1:37.3% BI:16.0%
> [libx264 @ 0x55b4064a0fc0] 8x8 transform intra:67.7% inter:37.2%
> [libx264 @ 0x55b4064a0fc0] direct mvs spatial:99.1% temporal:0.9%
> [libx264 @ 0x55b4064a0fc0] coded y,uvDC,uvAC intra: 82.9% 90.3% 84.8% 
> inter: 37.5% 31.7% 16.7%
> [libx264 @ 0x55b4064a0fc0] i16 v,h,dc,p: 42% 23% 5% 30%
> [libx264 @ 0x55b4064a0fc0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 18% 11% 14% 
> 7% 9% 11% 8% 11% 10%
> [libx264 @ 0x55b4064a0fc0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 18% 10% 12% 
> 8% 11% 12% 8% 11% 10%
> [libx264 @ 0x55b4064a0fc0] i8c dc,h,v,p: 43% 24% 20% 13%
> [libx264 @ 0x55b4064a0fc0] Weighted P-Frames: Y:5.7% UV:5.0%
> [libx264 @ 0x55b4064a0fc0] ref P L0: 46.1% 5.4% 17.1% 7.6% 6.9% 5.4% 
> 5.3% 3.0% 3.1% 0.0% 0.0%
> [libx264 @ 0x55b4064a0fc0] ref B L0: 70.6% 12.9% 6.2% 3.3% 2.6% 2.3% 
> 1.5% 0.6%
> [libx264 @ 0x55b4064a0fc0] ref B L1: 95.3% 4.7%
> [libx264 @ 0x55b4064a0fc0] kb/s:2939.38
> [aac @ 0x55b4062c2940] Qavg: 65385.453
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>



Links:
------
[1] http://eng
[2] https://github.com/bswebdk/FFQueue/issues/23#issuecomment-1877668990
[3]

**Comment by bswebdk** [comment]
Even though it is a workaround, you could fix the dual video files with: "ffmpeg -i dualvideo.mkv -map 0:v:0 -map 0:a -c copy singlevideo.mkv" - this should remux only first video stream and any audio track(s) into a new file.
