### ISSUE TITLE
[Feature Request] - "Presets" parameters, console options

### ISSUE THREAD

**Issue by Lirk88** [bswebdk/FFQueue#26]
It's strange, that "Advanced Cutting" doesn't works without saved Preset, it may have to use default FFmpeg parameters. In all "Preset" parameters need "None/Custom" selections in fields, e.g. for setting custom codecs, not presented in selection (libfdk_aac) and others... Also need global option "FFmpeg command line" from "Job Editor" to use FFmpeg with other tools, such as "sox" for normalizing audio: ffmpeg <%inputs%> -f wav -f wav -|sox.exe -t wav - -t wav - norm -0.1|ffmpeg <%inputs%> -i - <%preset%> -map 0:v -map 1:a <%output%>. So, global input and output console parameters with support <%inputs%> and <%output%> variables is better to add to the "Options" and "Presets".

**Comment by bswebdk** [comment]
Advanced Cutting requires a preset in order to be able to detect whether proper re-encoding is available. This has been done to protect the user against making errors that would make FFQueue appear to be broken.

FFQueue is a FFmpeg GUI, not a command line executor - even though some tricks are possible here and there.. Did you notice that FFQueue has an implementation of FFmpeg's audio normalizing filter? In the Preset Editor, go to the Filters tab, select Add => Audio => Normalization and choose your settings.
