### ISSUE TITLE
ID92 and ID814 can't be translated on windows, I fixed it.

### ISSUE THREAD

**Issue by adonais** [bswebdk/FFQueue#7]
[1.zip](https://github.com/bswebdk/FFQueue/files/3018923/1.zip)

**Comment by bswebdk** [comment]
Hi, and thanks for the hints. Your points are correct but your solutions are not. You cannot exchange "||" with "or" since "or" will not be recognized as a "command separator". Also, your solution to the issues with formatters is not portable since a translation file made on Linux would have %lld embedded and this may cause problems on Windows (pretty sure %lld works with gcc on Windoze, though). I have addressed both issues and fixed them for the next release. Thanks a lot for the "difficult to spot" bug report :)

**Comment by adonais** [comment]
In the code, SID_INVALID_CONSOLE_COMMAND is a string constant, and '%s' will not be replaced, so there's no problem.

**Comment by bswebdk** [comment]
SID_INVALID_CONSOLE_COMMAND is a message used when an invalid custom console command is entered in the options dialog. You can open options, enter "abc" in the "Custom console command" field and click "OK" to save - the message will display. Please review the docs, and you'll understand why "or" cannot replace "||": https://ffqueue.bruchhaus.dk/Documentation.aspx#cfg
